# Generated by Django 3.2.19 on 2023-08-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('Personal', 'Personal'), ('Escuela', 'Escuela'), ('Trabajo', 'Trabajo')], default='1', max_length=50)),
                ('relevant', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default='1', max_length=10)),
                ('color', models.CharField(choices=[('#DEE2E6', 'Blanco'), ('#CED3F2', 'Morado'), ('#D0F2E9', 'Verde'), ('#F2E8C9', 'Amarillo'), ('#F2CECE', 'Rosa'), ('#C7EFFB', 'Azul')], default='1', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
