# Generated by Django 3.2.19 on 2023-08-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='color',
            field=models.CharField(choices=[('#ffffff', 'Blanco'), ('#CED3F2', 'Morado'), ('#D0F2E9', 'Verde'), ('#F2E8C9', 'Amarillo'), ('#F2CECE', 'Rosa'), ('#d7dbdf', 'Gris')], default='1', max_length=10),
        ),
    ]
