# Generated by Django 3.2.19 on 2023-08-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='category',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Escuela', 'Escuela'), ('Trabajo', 'Trabajo')], default='Personal', max_length=50),
        ),
        migrations.AlterField(
            model_name='todo',
            name='color',
            field=models.CharField(choices=[('#ffffff', 'Blanco'), ('#CED3F2', 'Morado'), ('#D0F2E9', 'Verde'), ('#F2E8C9', 'Amarillo'), ('#F2CECE', 'Rosa'), ('#d7dbdf', 'Gris')], default='Blanco', max_length=10),
        ),
        migrations.AlterField(
            model_name='todo',
            name='relevant',
            field=models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default='Baja', max_length=10),
        ),
    ]
