# Generated by Django 3.2.19 on 2023-08-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20230813_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='color',
            field=models.CharField(choices=[('#ffffff', 'Blanco'), ('#CED3F2', 'Morado'), ('#D0F2E9', 'Verde'), ('#F2E8C9', 'Amarillo'), ('#F2CECE', 'Rosa'), ('#dee2e6', 'Gris')], default='Blanco', max_length=10),
        ),
    ]
